/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface ParkingInterface extends ethers.utils.Interface {
  functions: {
    "buyTicket(string,uint256,uint8,uint256)": FunctionFragment;
    "cancelTicket(string)": FunctionFragment;
    "getMemberDetails(address)": FunctionFragment;
    "getParkingZoneData(uint8)": FunctionFragment;
    "getTicket(string)": FunctionFragment;
    "isMember(address)": FunctionFragment;
    "isTicketValid(string,uint8)": FunctionFragment;
    "owner()": FunctionFragment;
    "pause()": FunctionFragment;
    "paused()": FunctionFragment;
    "registerMembership(string,string)": FunctionFragment;
    "renounceOwnership()": FunctionFragment;
    "revokeMemberships()": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
    "transferTicket(string,string,address)": FunctionFragment;
    "unpause()": FunctionFragment;
    "updateZonePriceForMember(uint256,uint8)": FunctionFragment;
    "updateZonePriceForNonMember(uint256,uint8)": FunctionFragment;
    "withdraw(uint256)": FunctionFragment;
    "zonePricePerMinute(uint8)": FunctionFragment;
    "zonePricePerMinuteForMember(uint8)": FunctionFragment;
    "zonePricePerMinuteForNonMember(uint8)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "buyTicket",
    values: [string, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "cancelTicket",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getMemberDetails",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getParkingZoneData",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "getTicket", values: [string]): string;
  encodeFunctionData(functionFragment: "isMember", values: [string]): string;
  encodeFunctionData(
    functionFragment: "isTicketValid",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "registerMembership",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "revokeMemberships",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "transferTicket",
    values: [string, string, string]
  ): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "updateZonePriceForMember",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "updateZonePriceForNonMember",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "withdraw",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "zonePricePerMinute",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "zonePricePerMinuteForMember",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "zonePricePerMinuteForNonMember",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "buyTicket", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "cancelTicket",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMemberDetails",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getParkingZoneData",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getTicket", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "isMember", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isTicketValid",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerMembership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revokeMemberships",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferTicket",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "updateZonePriceForMember",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateZonePriceForNonMember",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "withdraw", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "zonePricePerMinute",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "zonePricePerMinuteForMember",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "zonePricePerMinuteForNonMember",
    data: BytesLike
  ): Result;

  events: {
    "LogMemberRegistered(address,string,string,address,bool)": EventFragment;
    "LogMembershipRevoked(address)": EventFragment;
    "LogTicketBought(string,uint256,uint8)": EventFragment;
    "LogTicketCanceled(string,uint256)": EventFragment;
    "LogTicketRenewed(string,uint256,uint8)": EventFragment;
    "LogTicketTransferred(string,string)": EventFragment;
    "LogZonePriceChanged(uint256,uint256,uint8)": EventFragment;
    "OwnershipTransferred(address,address)": EventFragment;
    "Paused(address)": EventFragment;
    "Unpaused(address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "LogMemberRegistered"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "LogMembershipRevoked"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "LogTicketBought"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "LogTicketCanceled"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "LogTicketRenewed"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "LogTicketTransferred"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "LogZonePriceChanged"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Paused"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Unpaused"): EventFragment;
}

export type LogMemberRegisteredEvent = TypedEvent<
  [string, string, string, string, boolean] & {
    member: string;
    username: string;
    licensePlate: string;
    memberAddr: string;
    isRegistered: boolean;
  }
>;

export type LogMembershipRevokedEvent = TypedEvent<
  [string] & { member: string }
>;

export type LogTicketBoughtEvent = TypedEvent<
  [string, BigNumber, number] & {
    plate: string;
    numOfMinutes: BigNumber;
    zone: number;
  }
>;

export type LogTicketCanceledEvent = TypedEvent<
  [string, BigNumber] & { plate: string; balanceLeft: BigNumber }
>;

export type LogTicketRenewedEvent = TypedEvent<
  [string, BigNumber, number] & {
    plate: string;
    numOfMinutes: BigNumber;
    zone: number;
  }
>;

export type LogTicketTransferredEvent = TypedEvent<
  [string, string] & { oldPlate: string; newPlate: string }
>;

export type LogZonePriceChangedEvent = TypedEvent<
  [BigNumber, BigNumber, number] & {
    priceForMember: BigNumber;
    priceForNonMember: BigNumber;
    zone: number;
  }
>;

export type OwnershipTransferredEvent = TypedEvent<
  [string, string] & { previousOwner: string; newOwner: string }
>;

export type PausedEvent = TypedEvent<[string] & { account: string }>;

export type UnpausedEvent = TypedEvent<[string] & { account: string }>;

export class Parking extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: ParkingInterface;

  functions: {
    buyTicket(
      plate: string,
      numOfMinutes: BigNumberish,
      zone: BigNumberish,
      startTimestamp: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    cancelTicket(
      plate: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    getMemberDetails(
      member: string,
      overrides?: CallOverrides
    ): Promise<
      [string, string, string, boolean] & {
        username: string;
        licensePlate: string;
        memberAddr: string;
        isRegistered: boolean;
      }
    >;

    getParkingZoneData(
      zone: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber[], BigNumber[], boolean, BigNumber]>;

    getTicket(
      plate: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber, number]>;

    isMember(member: string, overrides?: CallOverrides): Promise<[boolean]>;

    isTicketValid(
      plate: string,
      zone: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    pause(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    paused(overrides?: CallOverrides): Promise<[boolean]>;

    registerMembership(
      username: string,
      licensePlate: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    revokeMemberships(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    transferTicket(
      oldPlate: string,
      newPlate: string,
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    unpause(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    updateZonePriceForMember(
      newPrice: BigNumberish,
      zone: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    updateZonePriceForNonMember(
      newPrice: BigNumberish,
      zone: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    withdraw(
      value: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    zonePricePerMinute(
      zone: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber] & {
        priceForNonMember: BigNumber;
        priceForMember: BigNumber;
      }
    >;

    zonePricePerMinuteForMember(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    zonePricePerMinuteForNonMember(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;
  };

  buyTicket(
    plate: string,
    numOfMinutes: BigNumberish,
    zone: BigNumberish,
    startTimestamp: BigNumberish,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  cancelTicket(
    plate: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  getMemberDetails(
    member: string,
    overrides?: CallOverrides
  ): Promise<
    [string, string, string, boolean] & {
      username: string;
      licensePlate: string;
      memberAddr: string;
      isRegistered: boolean;
    }
  >;

  getParkingZoneData(
    zone: BigNumberish,
    overrides?: CallOverrides
  ): Promise<[BigNumber[], BigNumber[], boolean, BigNumber]>;

  getTicket(
    plate: string,
    overrides?: CallOverrides
  ): Promise<[BigNumber, number]>;

  isMember(member: string, overrides?: CallOverrides): Promise<boolean>;

  isTicketValid(
    plate: string,
    zone: BigNumberish,
    overrides?: CallOverrides
  ): Promise<boolean>;

  owner(overrides?: CallOverrides): Promise<string>;

  pause(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  paused(overrides?: CallOverrides): Promise<boolean>;

  registerMembership(
    username: string,
    licensePlate: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  renounceOwnership(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  revokeMemberships(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  transferOwnership(
    newOwner: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  transferTicket(
    oldPlate: string,
    newPlate: string,
    newOwner: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  unpause(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  updateZonePriceForMember(
    newPrice: BigNumberish,
    zone: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  updateZonePriceForNonMember(
    newPrice: BigNumberish,
    zone: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  withdraw(
    value: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  zonePricePerMinute(
    zone: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, BigNumber] & {
      priceForNonMember: BigNumber;
      priceForMember: BigNumber;
    }
  >;

  zonePricePerMinuteForMember(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  zonePricePerMinuteForNonMember(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  callStatic: {
    buyTicket(
      plate: string,
      numOfMinutes: BigNumberish,
      zone: BigNumberish,
      startTimestamp: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    cancelTicket(plate: string, overrides?: CallOverrides): Promise<void>;

    getMemberDetails(
      member: string,
      overrides?: CallOverrides
    ): Promise<
      [string, string, string, boolean] & {
        username: string;
        licensePlate: string;
        memberAddr: string;
        isRegistered: boolean;
      }
    >;

    getParkingZoneData(
      zone: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber[], BigNumber[], boolean, BigNumber]>;

    getTicket(
      plate: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber, number]>;

    isMember(member: string, overrides?: CallOverrides): Promise<boolean>;

    isTicketValid(
      plate: string,
      zone: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;

    owner(overrides?: CallOverrides): Promise<string>;

    pause(overrides?: CallOverrides): Promise<void>;

    paused(overrides?: CallOverrides): Promise<boolean>;

    registerMembership(
      username: string,
      licensePlate: string,
      overrides?: CallOverrides
    ): Promise<void>;

    renounceOwnership(overrides?: CallOverrides): Promise<void>;

    revokeMemberships(overrides?: CallOverrides): Promise<void>;

    transferOwnership(
      newOwner: string,
      overrides?: CallOverrides
    ): Promise<void>;

    transferTicket(
      oldPlate: string,
      newPlate: string,
      newOwner: string,
      overrides?: CallOverrides
    ): Promise<void>;

    unpause(overrides?: CallOverrides): Promise<void>;

    updateZonePriceForMember(
      newPrice: BigNumberish,
      zone: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    updateZonePriceForNonMember(
      newPrice: BigNumberish,
      zone: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    withdraw(value: BigNumberish, overrides?: CallOverrides): Promise<void>;

    zonePricePerMinute(
      zone: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber] & {
        priceForNonMember: BigNumber;
        priceForMember: BigNumber;
      }
    >;

    zonePricePerMinuteForMember(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    zonePricePerMinuteForNonMember(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  filters: {
    "LogMemberRegistered(address,string,string,address,bool)"(
      member?: string | null,
      username?: null,
      licensePlate?: null,
      memberAddr?: null,
      isRegistered?: null
    ): TypedEventFilter<
      [string, string, string, string, boolean],
      {
        member: string;
        username: string;
        licensePlate: string;
        memberAddr: string;
        isRegistered: boolean;
      }
    >;

    LogMemberRegistered(
      member?: string | null,
      username?: null,
      licensePlate?: null,
      memberAddr?: null,
      isRegistered?: null
    ): TypedEventFilter<
      [string, string, string, string, boolean],
      {
        member: string;
        username: string;
        licensePlate: string;
        memberAddr: string;
        isRegistered: boolean;
      }
    >;

    "LogMembershipRevoked(address)"(
      member?: null
    ): TypedEventFilter<[string], { member: string }>;

    LogMembershipRevoked(
      member?: null
    ): TypedEventFilter<[string], { member: string }>;

    "LogTicketBought(string,uint256,uint8)"(
      plate?: string | null,
      numOfMinutes?: null,
      zone?: null
    ): TypedEventFilter<
      [string, BigNumber, number],
      { plate: string; numOfMinutes: BigNumber; zone: number }
    >;

    LogTicketBought(
      plate?: string | null,
      numOfMinutes?: null,
      zone?: null
    ): TypedEventFilter<
      [string, BigNumber, number],
      { plate: string; numOfMinutes: BigNumber; zone: number }
    >;

    "LogTicketCanceled(string,uint256)"(
      plate?: string | null,
      balanceLeft?: null
    ): TypedEventFilter<
      [string, BigNumber],
      { plate: string; balanceLeft: BigNumber }
    >;

    LogTicketCanceled(
      plate?: string | null,
      balanceLeft?: null
    ): TypedEventFilter<
      [string, BigNumber],
      { plate: string; balanceLeft: BigNumber }
    >;

    "LogTicketRenewed(string,uint256,uint8)"(
      plate?: string | null,
      numOfMinutes?: null,
      zone?: null
    ): TypedEventFilter<
      [string, BigNumber, number],
      { plate: string; numOfMinutes: BigNumber; zone: number }
    >;

    LogTicketRenewed(
      plate?: string | null,
      numOfMinutes?: null,
      zone?: null
    ): TypedEventFilter<
      [string, BigNumber, number],
      { plate: string; numOfMinutes: BigNumber; zone: number }
    >;

    "LogTicketTransferred(string,string)"(
      oldPlate?: string | null,
      newPlate?: null
    ): TypedEventFilter<
      [string, string],
      { oldPlate: string; newPlate: string }
    >;

    LogTicketTransferred(
      oldPlate?: string | null,
      newPlate?: null
    ): TypedEventFilter<
      [string, string],
      { oldPlate: string; newPlate: string }
    >;

    "LogZonePriceChanged(uint256,uint256,uint8)"(
      priceForMember?: null,
      priceForNonMember?: null,
      zone?: null
    ): TypedEventFilter<
      [BigNumber, BigNumber, number],
      { priceForMember: BigNumber; priceForNonMember: BigNumber; zone: number }
    >;

    LogZonePriceChanged(
      priceForMember?: null,
      priceForNonMember?: null,
      zone?: null
    ): TypedEventFilter<
      [BigNumber, BigNumber, number],
      { priceForMember: BigNumber; priceForNonMember: BigNumber; zone: number }
    >;

    "OwnershipTransferred(address,address)"(
      previousOwner?: string | null,
      newOwner?: string | null
    ): TypedEventFilter<
      [string, string],
      { previousOwner: string; newOwner: string }
    >;

    OwnershipTransferred(
      previousOwner?: string | null,
      newOwner?: string | null
    ): TypedEventFilter<
      [string, string],
      { previousOwner: string; newOwner: string }
    >;

    "Paused(address)"(
      account?: null
    ): TypedEventFilter<[string], { account: string }>;

    Paused(account?: null): TypedEventFilter<[string], { account: string }>;

    "Unpaused(address)"(
      account?: null
    ): TypedEventFilter<[string], { account: string }>;

    Unpaused(account?: null): TypedEventFilter<[string], { account: string }>;
  };

  estimateGas: {
    buyTicket(
      plate: string,
      numOfMinutes: BigNumberish,
      zone: BigNumberish,
      startTimestamp: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    cancelTicket(
      plate: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    getMemberDetails(
      member: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getParkingZoneData(
      zone: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getTicket(plate: string, overrides?: CallOverrides): Promise<BigNumber>;

    isMember(member: string, overrides?: CallOverrides): Promise<BigNumber>;

    isTicketValid(
      plate: string,
      zone: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    pause(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    paused(overrides?: CallOverrides): Promise<BigNumber>;

    registerMembership(
      username: string,
      licensePlate: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    revokeMemberships(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    transferTicket(
      oldPlate: string,
      newPlate: string,
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    unpause(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    updateZonePriceForMember(
      newPrice: BigNumberish,
      zone: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    updateZonePriceForNonMember(
      newPrice: BigNumberish,
      zone: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    withdraw(
      value: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    zonePricePerMinute(
      zone: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    zonePricePerMinuteForMember(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    zonePricePerMinuteForNonMember(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    buyTicket(
      plate: string,
      numOfMinutes: BigNumberish,
      zone: BigNumberish,
      startTimestamp: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    cancelTicket(
      plate: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    getMemberDetails(
      member: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getParkingZoneData(
      zone: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getTicket(
      plate: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    isMember(
      member: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    isTicketValid(
      plate: string,
      zone: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    pause(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    paused(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    registerMembership(
      username: string,
      licensePlate: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    revokeMemberships(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    transferTicket(
      oldPlate: string,
      newPlate: string,
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    unpause(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    updateZonePriceForMember(
      newPrice: BigNumberish,
      zone: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    updateZonePriceForNonMember(
      newPrice: BigNumberish,
      zone: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    withdraw(
      value: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    zonePricePerMinute(
      zone: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    zonePricePerMinuteForMember(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    zonePricePerMinuteForNonMember(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
